GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
        event.create('vod')
            .category('multiblock')
            .setEUIO('in')
            .setMaxIOSize(3, 3, 3, 3)
            .setProgressBar(GuiTextures.PROGRESS_BAR_EXTRACT, FillDirection.LEFT_TO_RIGHT)
            .setSound(GTSoundEntries.COOLING)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create("vacuum_pressure_vessel", "multiblock")
        .rotationState(RotationState.ALL)
        .recipeTypes(['vacuum_ejection', 'vod'])
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(GTBlocks.CASING_ALUMINIUM_FROSTPROOF)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("AABBBAA", "AABBBAA", "AABCBAA", "AABCBAA", "AABCBAA", "AABCBAA", "AABBBAA", "AABBBAA", "AAAAAAA", "AAAAAAA")
            .aisle("ABBBBBA", "ABAAABA", "ABAAABA", "ABAAABA", "ABAAABA", "ABAAABA", "ABAAABA", "ABBBBBA", "AAAAAAA", "AAAAAAA")
            .aisle("BBBBBBB", "BAEAEAB", "BAFFFAB", "BAFFFAB", "BAFFFAB", "BAAAAAB", "BAAAAAB", "BBBBBBB", "AAEAAAA", "AAEAAAA")
            .aisle("BBBBBBB", "BAAAAAB", "CAFFFAC", "CAFAFAC", "CAFGFAC", "CAAGAAB", "BAAGGGG", "BBABGBB", "AEAEAAA", "AEAEAAA")
            .aisle("BBBBBBB", "BAEAEAB", "BAFFFAB", "BAFFFAB", "BAFFFAB", "BAAAAAB", "BAAAAAB", "BBBBBBB", "AAEAAAA", "AAEAAAA")
            .aisle("ABBBBBA", "ABAAABA", "ABAAABA", "ABAAABA", "ABAAABA", "ABAAABA", "ABAAABA", "ABBBBBA", "AAAAAAA", "AAAAAAA")
            .aisle("AAB@BAA", "AABBBAA", "AABCBAA", "AABCBAA", "AABCBAA", "AABCBAA", "AABBBAA", "AABBBAA", "AAAAAAA", "AAAAAAA")
               .where("A", Predicates.any())
               .where("B", Predicates.blocks("gtceu:frostproof_machine_casing").setMinGlobalLimited(140)
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                    .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                    .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                    .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                    .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                    .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
               .where("C", Predicates.blocks("gtceu:tempered_glass"))
               .where("E", Predicates.blocks("gtceu:steel_frame"))
               .where("F", Predicates.blocks("gtceu:solid_machine_casing"))
               .where("G", Predicates.blocks("gtceu:steel_pipe_casing"))
               .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_frost_proof', 'gtceu:block/multiblock/vacuum_freezer');

})