ServerEvents.recipes(event => {
    event.shaped('gtceu:heavy_drilling_rig', [
    'CPC',
    'VHV',
    'MDM',
], { P: "gtceu:lv_pump", C: "#gtceu:circuits/lv", V: "gtceu:lv_conveyor_module", H: "gtceu:lv_miner", M: "gtceu:lv_electric_motor", D: "gtceu:steel_drill_head"})
    event.recipes.gtceu.heavy_drilling_rig('crude_ore_slurry_from_drilling')
        .chancedInput('gtceu:steel_drill_head', 2000, 0)
        .inputFluids('gtceu:drilling_fluid 4000')
        .outputFluidsRanged('gtceu:crude_ore_slurry', 500, 1000)
        .itemOutputsRanged('gtsac:geode_cluster', 1, 4)
        .duration(15*20)
        .EUt(64)

    event.recipes.gtceu.electrolyzer('crude_ore_slurry')
        .inputFluids('gtceu:crude_ore_slurry 2000')
        .outputFluids('gtceu:clean_ore_slurry 1000')
        .itemOutputsRanged('gtceu:raw_magnetite', 2, 4)
        .itemOutputsRanged('gtceu:raw_chalcopyrite', 2, 4)
        .itemOutputsRanged('gtceu:raw_coal', 2, 4)
        .itemOutputsRanged('gtceu:raw_cassiterite', 2, 4)
        .duration(17*20)
        .EUt(120)
    
    event.recipes.gtceu.clarifier('clean_ore_slurry')
        .inputFluids('gtceu:clean_ore_slurry 500')
        .outputFluids('gtceu:refined_ore_slurry 750')
        .itemOutputs('3x gtceu:low_density_crust_sludge_dust', '2x gtceu:high_density_crust_sludge_dust')
        .duration(15*20)
        .EUt(120)
    
    event.recipes.gtceu.filtrator('refined_ore_slurry')
        .inputFluids('gtceu:refined_ore_slurry 1000')
        .itemOutputsRanged('gtceu:low_density_crust_sludge_dust', 4, 11)
        .itemOutputsRanged('gtceu:high_density_crust_sludge_dust', 2, 7)
        .itemOutputsRanged('gtceu:raw_silver', 2, 4)
        .duration(11*20)
        .EUt(480)

    event.recipes.gtceu.dissolution_chamber('low_density_crust_sludge_dust')
        .itemInputs('7x gtceu:low_density_crust_sludge_dust')
        .inputFluids('gtceu:hydrochloric_acid 3000')
        .itemOutputsRanged('gtceu:raw_vanadium_magnetite', 2, 4)
        .itemOutputsRanged('gtceu:raw_galena', 2, 4)
        .itemOutputsRanged('minecraft:raw_gold', 2, 4)
        .outputFluids('gtceu:crust_waste 500')
        .duration(18*20)
        .EUt(480)

    event.recipes.gtceu.dissolution_chamber('high_density_crust_sludge_dust')
        .itemInputs('5x gtceu:high_density_crust_sludge_dust')
        .inputFluids('gtceu:hydrochloric_acid 5000')
        .itemOutputsRanged('gtceu:raw_cobaltite', 2, 4)
        .itemOutputsRanged('gtceu:raw_sphalerite', 2, 4)
        .itemOutputsRanged('gtceu:raw_chromite', 2, 4)
        .outputFluids('gtceu:crust_waste 800')
        .duration(23*20)
        .EUt(1920)

    event.recipes.gtceu.centrifuge('crust_waste')
        .inputFluids('gtceu:crust_waste 2000')
        .outputFluids('minecraft:water 1000')
        .itemOutputsRanged('gtceu:crushed_trona_ore', 4, 7)
        .itemOutputsRanged('gtceu:crushed_lepidolite_ore', 4, 7)
        .duration(9*20)
        .EUt(120)

    event.recipes.gtceu.sifter('geode_cluster')
        .itemInputs('gtsac:geode_cluster')
        .itemOutputsRanged('gtceu:raw_sapphire', 1, 4)
        .itemOutputsRanged('gtceu:raw_apatite', 1, 4)
        .itemOutputsRanged('gtceu:raw_diamond', 1, 4)
        .itemOutputsRanged('gtceu:raw_emerald', 1, 4)
        .itemOutputsRanged('gtceu:raw_topaz', 1, 4)
        .itemOutputsRanged('gtceu:raw_realgar', 1, 4)
        .duration(21*20)
        .EUt(120)

    //MANTLE ORE PROC

    const min = 4
    const max = 9
    event.recipes.gtceu.extreme_pressure_drilling_rig('mantle_drilling')
        .chancedInput('gtceu:tungsten_steel_drill_head', 500, 0)
        .inputFluids('gtceu:drilling_fluid 20000', 'gtceu:liquid_oxygen 16000')
        .outputFluidsRanged('gtceu:inchoate_mantle_slurry', 16000, 26000)
        .outputFluidsRanged('gtceu:magnesium_rich_oxide_mixture', 12000, 18000)
        .duration(120*20)
        .EUt(7680)

    //MAGNESIUM OXIDE MIXTURE

    event.recipes.gtceu.neutralization('neutralized_inane_oxide_mixture')
        .inputFluids('gtceu:aqua_regia 2000', 'gtceu:magnesium_rich_oxide_mixture 4000')
        .outputFluids('gtceu:diluted_hydrochloric_acid 1000', 'gtceu:neutralized_inane_oxide_mixture 5000')
        .itemOutputsRanged('gtceu:crushed_olivine_ore', 4, 9)
        .duration(23*20)
        .EUt(1920)

    event.recipes.gtceu.leaching_plant('dissolved_inane_oxide_mixture')
        .inputFluids('gtceu:neutralized_inane_oxide_mixture 30000', 'gtceu:nitric_acid 10000')
        .outputFluids('gtceu:dissolved_inane_oxide_mixture 30000', 'gtceu:crust_waste 15000')
        .duration(237*20)
        .EUt(1230)

    event.recipes.gtceu.electrolyzer('dissolved_inane_oxide_mixture_electrolyzer')
        .inputFluids('gtceu:dissolved_inane_oxide_mixture 4000')
        .itemOutputsRanged('gtceu:magnesia_dust', 8, 14)
        .itemOutputsRanged('gtceu:bauxite_dust', 6, 9)
        .itemOutputsRanged('gtceu:silicon_dioxide_dust', 7, 13)
        .itemOutputsRanged('gtceu:iron_oxide_dust', 5, 11)
        .duration(17*20)
        .EUt(1920)

    //MANTLE SLURRY PROCESSING

    event.recipes.gtceu.centrifuge('purified_mantle_slurry')
        .inputFluids('gtceu:inchoate_mantle_slurry 6000')
        .outputFluids('gtceu:purified_mantle_slurry 5000', 'gtceu:magnesium_rich_oxide_mixture 1000')
        .duration(14*20)
        .EUt(1920)

    event.recipes.gtceu.distillation_tower('mantle_slurries_distillation')
        .inputFluids('gtceu:purified_mantle_slurry 18000')
        .outputFluids('gtceu:strongly_bonded_carbide_fluoride_slurry 4500')
        .outputFluids('gtceu:native_element_slurry 4500')
        .outputFluids('gtceu:unrefined_sulfuric_mineral_slurry 4500')
        .outputFluids('gtceu:impurity_bristled_valuable_oxide_slurry 4500')
        .duration(130*20)
        .EUt(8192)

    //VALUABLE OXIDES PROCESSING

    event.recipes.gtceu.leaching_plant('leached_valuable_oxide_slurry')
        .inputFluids('gtceu:impurity_bristled_valuable_oxide_slurry 28000')
        .inputFluids('gtceu:sulfuric_acid 4000', 'gtceu:hydrochloric_acid 3000')
        .outputFluids('gtceu:leached_valuable_oxide_slurry 22000')
        .outputFluids('gtceu:diluted_sulfuric_acid 2000', 'gtceu:diluted_hydrochloric_acid 1500')
        .duration(124*20)
        .EUt(1920)

    event.recipes.gtceu.electric_arc_furnace('crvos_prvos')
        .inputFluids('gtceu:leached_valuable_oxide_slurry 4000')
        .inputFluids('gtceu:carbon_monoxide 1000')
        .outputFluids('gtceu:carbon_reduced_valuable_oxide_slurry 2000')
        .outputFluids('gtceu:partially_reduced_valuable_oxide_slurry 2000')
        .outputFluids('gtceu:carbon_dioxide 1000')
        .duration(11*20)
        .EUt(480)

    event.recipes.gtceu.centrifuge('carbon_reduced_valuable_oxide_slurry_centrifuging')
        .inputFluids('gtceu:carbon_reduced_valuable_oxide_slurry 2000')
        .itemOutputsRanged('gtceu:raw_tantalite', min, max)
        .itemOutputsRanged('gtceu:raw_tricalcium_phosphate', min, max)
        .itemOutputsRanged('gtceu:raw_wulfenite', min, max)
        .itemOutputsRanged('gtceu:raw_pyrolusite', min, max)
        .outputFluidsRanged('gtceu:mantle_waste', 400, 800)
        .duration(15*20)
        .EUt(1920)

    event.recipes.gtceu.rotary_kiln('hrs_svos')
        .inputFluids('gtceu:partially_reduced_valuable_oxide_slurry 4000')
        .inputFluids('gtceu:hydrogen 1500')
        .outputFluids('gtceu:hydrogen_reduced_valuable_oxide_slurry 3000')
        .outputFluids('gtceu:sparse_valuable_oxide_slurry 1000')
        .outputFluids('minecraft:water 3000')
        .duration(12*20)
        .EUt(480)

    event.recipes.gtceu.centrifuge('hydrogen_reduced_valuable_oxide_slurry_centrifuging')
        .inputFluids('gtceu:hydrogen_reduced_valuable_oxide_slurry 2000')
        .itemOutputsRanged('gtceu:raw_scheelite', min, max)
        .itemOutputsRanged('gtceu:raw_pitchblende', min, max)
        .itemOutputsRanged('gtceu:raw_tungstate', min, max)
        .itemOutputsRanged('gtceu:raw_uraninite', min, max)
        .outputFluidsRanged('gtceu:mantle_waste', 400, 800)
        .duration(17*20)
        .EUt(1920)

    event.recipes.gtceu.electrolyzer('sparse_valuable_oxide_slurry_electrolyzing')
        .inputFluids('gtceu:sparse_valuable_oxide_slurry 2500')
        .itemOutputsRanged('gtceu:raw_ilmenite', min, max)
        .itemOutputsRanged('gtceu:raw_monazite', min, max)
        .outputFluidsRanged('gtceu:mantle_waste', 400, 800)
        .duration(9*20)
        .EUt(1920)

    //SULFURIC MINERALS PROCESSING

    event.recipes.gtceu.froth_flotation_plant('sulfuric_mineral_froth')
        .inputFluids('gtceu:unrefined_sulfuric_mineral_slurry 24000')
        .inputFluids('minecraft:water 96000', 'gtceu:air 48000')
        .itemInputs('63x gtceu:sodium_ethyl_xanthate_dust')
        .outputFluids('gtceu:sulfuric_mineral_froth 48000')
        .outputFluids('gtceu:mantle_waste 6000')
        .duration(157*20)
        .EUt(7680)

    event.recipes.gtceu.rotary_kiln('desulfurized_sulfuric_mineral_froth')
        .inputFluids('gtceu:sulfuric_mineral_froth 5000')
        .inputFluids('gtceu:oxygen 8000')
        .outputFluids('gtceu:desulfurized_sulfuric_mineral_froth 3000')
        .outputFluids('gtceu:sulfur_dioxide 4000')
        .duration(17*20)
        .EUt(1920)

    event.recipes.gtceu.electric_arc_furnace('reduced_sulfuric_mineral_froth')
        .inputFluids('gtceu:desulfurized_sulfuric_mineral_froth 6000')
        .inputFluids('gtceu:carbon_monoxide 2000')
        .itemInputs('3x gtceu:calcium_dust')
        .outputFluids('gtceu:reduced_sulfuric_mineral_froth 5000')
        .outputFluids('gtceu:carbon_dioxide 1000')
        .itemOutputs('4x gtceu:oxide_slag_dust')
        .duration(23*20)
        .EUt(1920)

    event.recipes.gtceu.centrifuge('reduced_sulfuric_mineral_froth_centrifuging')
        .inputFluids('gtceu:reduced_sulfuric_mineral_froth 2000')
        .itemOutputsRanged('gtceu:raw_pyrite', min, max)
        .itemOutputsRanged('gtceu:raw_cinnabar', min, max)
        .itemOutputsRanged('gtceu:raw_stibnite', min, max)
        .itemOutputsRanged('gtceu:raw_barite', min, max)
        .itemOutputsRanged('gtceu:raw_molybdenite', min, max)
        .itemOutputsRanged('gtceu:raw_cooperite', min, max)
        .duration(17*20)
        .EUt(1920)

    event.recipes.gtceu.centrifuge('native_element_slurry_centrifuging')
        .inputFluids('gtceu:native_element_slurry 5000')
        .outputFluids('gtceu:crust_waste 1000')
        .outputFluids('gtceu:dirty_magnetic_element_slurry 2000')
        .outputFluids('gtceu:dirty_heavy_element_slurry 2000')
        .duration(15*20)
        .EUt(1920)

    event.recipes.gtceu.large_fluid_electromagnet('magnetic_element_slurry_separating')
        .inputFluids('gtceu:dirty_magnetic_element_slurry 3000')
        .outputFluids('gtceu:mantle_waste 1000')
        .itemOutputs('3x gtceu:low_purity_magnetic_element_concentrate_dust')
        .itemOutputs('gtceu:high_purity_magnetic_element_concentrate_dust')
        .duration(17*20)
        .EUt(1920)

    event.recipes.gtceu.electromagnetic_separator('low_purity_magnetic_element_separating')
        .itemInputs('5x gtceu:low_purity_magnetic_element_concentrate_dust')
        .itemOutputs('3x gtceu:high_purity_magnetic_element_concentrate_dust')
        .duration(9*20)
        .EUt(1920)

    event.recipes.gtceu.large_fluid_sifting_funnel('heavy_element_slurry_separating')
        .inputFluids('gtceu:dirty_heavy_element_slurry 3000')
        .outputFluids('gtceu:mantle_waste 1000')
        .itemOutputs('3x gtceu:low_purity_heavy_element_concentrate_dust')
        .itemOutputs('gtceu:high_purity_heavy_element_concentrate_dust')
        .duration(17*20)
        .EUt(1920)

    event.recipes.gtceu.sifter('low_purity_heavy_element_separating')
        .itemInputs('5x gtceu:low_purity_heavy_element_concentrate_dust')
        .itemOutputs('3x gtceu:high_purity_heavy_element_concentrate_dust')
        .duration(9*20)
        .EUt(1920)

    event.recipes.gtceu.centrifuge('magnetic_element_centrifuging')
        .itemInputs('4x gtceu:high_purity_magnetic_element_concentrate_dust')
        .itemOutputsRanged('gtceu:raw_cobalt', min, max)
        .itemOutputsRanged('gtceu:raw_thorium', min, max)
        .itemOutputsRanged('gtceu:raw_neodymium', min, max)
        .itemOutputsRanged('gtceu:raw_plutonium', min, max)
        .duration(12*20)
        .EUt(7960)

    event.recipes.gtceu.electrolyzer('heavy_element_centrifuging')
        .itemInputs('4x gtceu:high_purity_heavy_element_concentrate_dust')
        .itemOutputsRanged('gtceu:raw_graphite', min, max)
        .itemOutputsRanged('gtceu:raw_platinum', min, max)
        .itemOutputsRanged('gtceu:raw_palladium', min, max)
        .itemOutputsRanged('gtceu:raw_beryllium', min, max)
        .duration(12*20)
        .EUt(7960)

    


    

})