ServerEvents.recipes(event => {
    event.shaped('gtceu:heavy_drilling_rig', [
    'CPC',
    'VHV',
    'MDM',
], { P: "gtceu:lv_pump", C: "#gtceu:circuits/lv", V: "gtceu:lv_conveyor_module", H: "gtceu:lv_miner", M: "gtceu:lv_electric_motor", D: "gtceu:steel_drill_head"})
    event.recipes.gtceu.heavy_drilling_rig('crude_ore_slurry_from_drilling')
        .chancedInput('gtceu:steel_drill_head', 2000, 0)
        .inputFluids('gtceu:drilling_fluid 4000')
        .outputFluidsRanged('gtceu:crude_ore_slurry', 500, 1000)
        .itemOutputsRanged('gtsac:geode_cluster', 1, 4)
        .duration(15*20)
        .EUt(64)
//TODO: move most of these to clarifier and purification tank
    event.recipes.gtceu.electrolyzer('crude_ore_slurry')
        .inputFluids('gtceu:crude_ore_slurry 2000')
        .outputFluids('gtceu:clean_ore_slurry 1000')
        .itemOutputsRanged('gtceu:raw_magnetite', 2, 4)
        .itemOutputsRanged('gtceu:raw_chalcopyrite', 2, 4)
        .itemOutputsRanged('gtceu:raw_coal', 2, 4)
        .itemOutputsRanged('gtceu:raw_cassiterite', 2, 4)
        .duration(10*20)
        .EUt(120)
    
    event.recipes.gtceu.clarifier('clean_ore_slurry')
        .inputFluids('gtceu:clean_ore_slurry 500')
        .outputFluids('gtceu:refined_ore_slurry 750')
        .itemOutputs('3x gtceu:low_density_crust_sludge_dust', '2x gtceu:high_density_crust_sludge_dust')
        .duration(15*20)
        .EUt(120)
    
    event.recipes.gtceu.filtrator('refined_ore_slurry')
        .inputFluids('gtceu:refined_ore_slurry 1000')
        .itemOutputsRanged('gtceu:low_density_crust_sludge_dust', 4, 11)
        .itemOutputsRanged('gtceu:high_density_crust_sludge_dust', 2, 7)
        .duration(10*20)
        .EUt(480)

    event.recipes.gtceu.dissolution_chamber('low_density_crust_sludge_dust')
        .itemInputs('7x gtceu:low_density_crust_sludge_dust')
        .inputFluids('gtceu:hydrochloric_acid 3000')
        .itemOutputsRanged('gtceu:raw_vanadium_magnetite', 2, 4)
        .itemOutputsRanged('gtceu:raw_galena', 2, 4)
        .itemOutputsRanged('minecraft:raw_gold', 2, 4)
        .outputFluids('gtceu:crust_waste 500')
        .duration(20*20)
        .EUt(480)

    event.recipes.gtceu.dissolution_chamber('high_density_crust_sludge_dust')
        .itemInputs('5x gtceu:high_density_crust_sludge_dust')
        .inputFluids('gtceu:hydrochloric_acid 5000')
        .itemOutputsRanged('gtceu:raw_cobaltite', 2, 4)
        .itemOutputsRanged('gtceu:raw_sphalerite', 2, 4)
        .itemOutputsRanged('gtceu:raw_chromite', 2, 4)
        .outputFluids('gtceu:crust_waste 800')
        .duration(20*20)
        .EUt(1920)

    event.recipes.gtceu.centrifuge('crust_waste')
        .inputFluids('gtceu:crust_waste 2000')
        .outputFluids('minecraft:water 1000')
        .itemOutputsRanged('gtceu:trona_dust', 4, 7)
        .itemOutputsRanged('gtceu:lepidolite_dust', 4, 7)
        .duration(10*20)
        .EUt(120)

    event.recipes.gtceu.sifter('geode_cluster')
        .itemInputs('gtsac:geode_cluster')
        .itemOutputsRanged('gtceu:raw_sapphire', 1, 4)
        .itemOutputsRanged('gtceu:raw_apatite', 1, 4)
        .itemOutputsRanged('gtceu:raw_diamond', 1, 4)
        .itemOutputsRanged('gtceu:raw_emerald', 1, 4)
        .itemOutputsRanged('gtceu:raw_topaz', 1, 4)
        .itemOutputsRanged('gtceu:raw_realgar', 1, 4)
        .duration(20*20)
        .EUt(120)
})