ServerEvents.recipes(event => {
    event.recipes.gtceu.mixer('ferrochromium')
        .itemInputs('gtceu:hematite_dust', 'gtceu:chromium_dust')
        .itemOutputs('2x gtceu:ferrochromium_dust')
        .duration(5*20)
        .EUt(120)

    event.recipes.gtceu.mixer('ferromanganese')
        .itemInputs('gtceu:iron_dust', 'gtceu:manganese_dust')
        .itemOutputs('gtceu:ferromanganese_dust')
        .duration(5*20)
        .EUt(120)

    event.recipes.gtceu.electric_arc_furnace('high_carbon_stainless_steel')
        .itemInputs('5x gtceu:steel_dust', '2x gtceu:ferromanganese_dust', '1x gtceu:ferrochromium_dust', '1x gtceu:carbon_dust')
        .outputFluids('gtceu:high_carbon_stainless_steel 1296')

        .duration(42*20)
        .EUt(480)

    event.recipes.gtceu.electric_blast_furnace('clean_stainless_steel')
        .inputFluids('gtceu:high_carbon_stainless_steel 432')
        .outputFluids('gtceu:clean_stainless_steel 432')
        .itemOutputs('2x gtceu:oxide_slag_dust')
        .duration(20*20)
        .EUt(480)
        .blastFurnaceTemp(2670)

    event.recipes.gtceu.vod('ultra_low_carbon_stainless_steel')
        .inputFluids('gtceu:clean_stainless_steel 288')
        .perTick(true).inputFluids('gtceu:oxygen 20')
        .perTick(false).outputFluids('gtceu:ultra_low_carbon_stainless_steel 288')
        .duration(15*20)
        .EUt(512)
    
    event.recipes.gtceu.vod('chemically_final_molten_stainless_steel')
        .inputFluids('gtceu:ultra_low_carbon_stainless_steel 288')
        .notConsumable('gtceu:quicklime_dust')
        .itemInputs('3x gtceu:silicon_dust')
        .itemOutputs('9x gtceu:silicon_dioxide_dust')
        .outputFluids('gtceu:chemically_final_molten_stainless_steel 288')
        .duration(30*20)
        .EUt(128)

    event.recipes.gtceu.chemical_bath('untreated_stainless_steel_ingot')
        .inputFluids('gtceu:chemically_final_molten_stainless_steel 144')
        .notConsumable('gtceu:ingot_casting_mold')
        .itemOutputs('gtsac:untreated_stainless_steel_ingot')
        .duration(51*20)
        .EUt(120)

    event.recipes.gtceu.chemical_bath('stainless_steel_ingot_treating')
        .itemInputs('gtsac:untreated_stainless_steel_ingot')
        .inputFluids('gtceu:distilled_water 750')
        .itemOutputs('gtceu:stainless_steel_ingot')
        .outputFluids('gtceu:steam 2500')
        .duration(5*20)
        .EUt(120)
})