GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
        event.create('rotary_kiln')
            .category('multiblock')
            .setEUIO('in')
            .setMaxIOSize(2, 2, 2, 2)
            .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
            .setSound(GTSoundEntries.FURNACE)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('rotary_kiln', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('rotary_kiln')
        .appearanceBlock(GTBlocks.LIGHT_CONCRETE)
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK_SUBTICK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
                .aisle("BBBBBBB", "BBBBBBB", "BBMMMBB", "BBMMMBB", "BBMMMBB", "BBBBBBB", "BBBBBBB")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("ADAAADA", "ADDDDDA", "ADEEEDA", "ADEFEDA", "ADEEEDA", "ADDDDDA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADEFEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("ADAAADA", "ADDDDDA", "ADEEEDA", "ADEFEDA", "ADEEEDA", "ADDDDDA", "AAAAAAA")
                .aisle("CAAAAAC", "CAACAAC", "CCCCCCC", "ACCACCA", "AACCCAA", "AAACAAA", "AAAAAAA")
                .aisle("ADAAADA", "ADDDDDA", "ADEEEDA", "ADECEDA", "ADEEEDA", "ADDDDDA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("ADAAADA", "ADDDDDA", "ADEEEDA", "ADECEDA", "ADEEEDA", "ADDDDDA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("AAAAAAA", "AAADAAA", "AAEEEAA", "ADECEDA", "AAEEEAA", "AAADAAA", "AAAAAAA")
                .aisle("BBBBBBB", "BBBBBBB", "BBMMMBB", "BBM@MBB", "BBMMMBB", "BBBBBBB", "BBBBBBB")
            .where("A", Predicates.any())
            .where("B", Predicates.blocks("gtceu:light_concrete"))
            .where("C", Predicates.blocks("gtceu:steel_gearbox"))
            .where("D", Predicates.blocks("gtceu:steel_frame"))
            .where("E", Predicates.blocks("gtceu:rotary_kiln_bricks"))
            .where("F", Predicates.blocks("gtceu:steel_pipe_casing"))
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .where("M", Predicates.blocks("gtceu:steel_gearbox")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
            .build())
        .workableCasingModel('gtceu:block/casings/gearbox/machine_casing_gearbox_steel', 'gtceu:block/machines/rotary_kiln')

})