GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
        event.create('clarifier')
            .category('multiblock')
            .setEUIO('in')
            .setMaxIOSize(3, 3, 3, 3)
            .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
            .setSound(GTSoundEntries.BATH)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('clarifier', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('clarifier')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK_SUBTICK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
                .aisle("AAACCCCCAAA", "AAABBBBBAAA", "AAABBBBBAAA", "AAABBBBBAAA")
                .aisle("AACBBBBBCAA", "AABAAAAABAA", "AABAADAABAA", "AABAADAABAA")
                .aisle("ACBBBBBBBCA", "ABAAAAAAABA", "ABAAAAAAABA", "ABAAADAAABA")
                .aisle("CBBBBBBBBBC", "BAAAAAAAAAB", "BAAAADAAAAB", "BAAAADAAAAB")
                .aisle("CBBBBBBBBBC", "BAAAAEAAAAB", "BAAAAEAAAAB", "BAAAADAAAAB")
                .aisle("CBBBBBBBBBC", "BAAAEEEAAAB", "BDADEEEDADB", "BDDDDDDDDDB")
                .aisle("CBBBBBBBBBC", "BAAAAEAAAAB", "BAAAAEAAAAB", "BAAAADAAAAB")
                .aisle("CBBBBBBBBBC", "BAAAAAAAAAB", "BAAAADAAAAB", "BAAAADAAAAB")
                .aisle("ACBBBBBBBCA", "ABAAAAAAABA", "ABAAAAAAABA", "ABAAADAAABA")
                .aisle("AACBBBBBCAA", "AABAAAAABAA", "AABAADAABAA", "AABAADAABAA")
                .aisle("AAACCCCCAAA", "AAABBBBBAAA", "AAABBFBBAAA", "AAABBBBBAAA")
            .where("A", Predicates.blocks("minecraft:air").or(Predicates.blocks("minecraft:cave_air")))
            .where("C", Predicates.blocks("gtceu:steel_firebox_casing"))
            .where("F", Predicates.controller(Predicates.blocks(definition.get())))
            .where("B", Predicates.blocks("gtceu:solid_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
            .where("D", Predicates.blocks("gtceu:steel_pipe_casing"))
            .where("E", Predicates.blocks("gtceu:steel_gearbox"))
                .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_solid_steel', 'gtceu:block/machines/electric_winding_machine')

})