GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
        event.create('filtrator')
            .category('multiblock')
            .setEUIO('in')
            .setMaxIOSize(3, 3, 3, 3)
            .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
            .setSound(GTSoundEntries.ELECTROLYZER)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('filtration_unit', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('filtrator')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK_SUBTICK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("BAAAB", "BAAAB", "BAAAB", "BAAAB", "ABBBA")
            .aisle("AAAAA", "ACCCA", "ADEDA", "ADDDA", "AABAA")
            .aisle("AAAAA", "ACDCA", "ADEDA", "ADDDA", "AABAA")
            .aisle("BAAAB", "BCDCB", "BDEDB", "BDDDB", "ABBBA")
            .aisle("AAAAA", "ACDCA", "ADEDA", "ADDDA", "AABAA")
            .aisle("AAAAA", "ACCCA", "ADFDA", "ADDDA", "AABAA")
            .aisle("BAAAB", "BAAAB", "BAAAB", "BAAAB", "ABBBA")
        .where("A", Predicates.any())
        .where("B", Predicates.blocks("gtceu:steel_frame"))
        .where("C", Predicates.blocks("gtceu:steel_firebox_casing"))
        .where("D", Predicates.blocks("gtceu:solid_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
        .where("E", Predicates.blocks("gtceu:steel_pipe_casing"))
        .where("F", Predicates.controller(Predicates.blocks(definition.get())))
        .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_solid_steel', 'gtceu:block/machines/electric_winding_machine')
})