GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('polymerization_tank')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(2, 2, 2, 2)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH)
});

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create("polymerization_tank", "multiblock")
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('polymerization_tank')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK_SUBTICK), GTRecipeModifiers.BATCH_MODE])
        .pattern(definition => FactoryBlockPattern.start()
                .aisle("BAB", "CCC", "DDD", "DDD", "DDD", "CCC")
                .aisle("AAA", "CCC", "DED", "DED", "DED", "CCC")
                .aisle("BAB", "CCC", "D@D", "DDD", "DDD", "CCC")
            .where("A", Predicates.blocks("minecraft:air"))
            .where("B", Predicates.blocks("gtceu:steel_frame"))
            .where("C", Predicates.blocks("gtceu:steel_machine_casing"))
            .where("D", Predicates.blocks("gtceu:solid_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
            .where("E", Predicates.blocks("gtceu:steel_pipe_casing"))
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
        .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_solid_steel', 'gtceu:block/machines/electric_winding_machine');
})