GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
        event.create('electric_arc_furnace')
            .category('multiblock')
            .setEUIO('in')
            .setMaxIOSize(6, 3, 0, 2)
            .setProgressBar(GuiTextures.PROGRESS_BAR_ARC_FURNACE, FillDirection.LEFT_TO_RIGHT)
            .setSound(GTSoundEntries.ARC)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create("electric_arc_furnace", "multiblock")
        .machine((holder) => new $CoilWorkableElectricMultiblockMachine(holder))
        .rotationState(RotationState.ALL)
        .recipeTypes(['arc_furnace', 'electric_arc_furnace'])
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, GTRecipeModifiers.BATCH_MODE, (machine, recipe) => $GTSACRecipeModifiers.electricArcFurnaceCoilOverclock(machine, recipe)])
        .appearanceBlock(GTBlocks.CASING_INVAR_HEATPROOF)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("ABBBA", "ABCBA", "ABCBA", "ABCBA", "ABCBA", "ABBBA")
            .aisle("BBBBB", "BEAEB", "BEAEB", "BEAEB", "BEAEB", "BBBBB")
            .aisle("BBBBB", "CAAAC", "CAAAC", "CAAAC", "CAAAC", "BBFBB")
            .aisle("BBBBB", "BAEAB", "BAEAB", "BAEAB", "BAEAB", "BBBBB")
            .aisle("AB@BA", "ABCBA", "ABCBA", "ABCBA", "ABCBA", "ABBBA")
               .where("A", Predicates.any())
               .where("B", Predicates.blocks("gtceu:heatproof_machine_casing").setMinGlobalLimited(60)
                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                    .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                    .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                    .or(Predicates.abilities(PartAbility.EXPORT_ITEMS))
                    .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                    .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
               .where("C", Predicates.heatingCoils())
               .where("E", Predicates.blocks("gtceu:steel_pipe_casing"))
               .where("F", Predicates.abilities(PartAbility.MUFFLER).setExactLimit(1))
               .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_heatproof', 'gtceu:block/machines/arc_furnace');

})