GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('advanced_steam_mining_rig')
        .category('primitive')
        .setMaxIOSize(2, 6, 1, 0)
        .setProgressBar($GTSACGuiTextures.PROGRESS_BAR_DRILL, FillDirection.UP_TO_DOWN)
        .setSound(GTSoundEntries.JET_ENGINE)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create("advanced_steam_mining_rig", "primitive")  
        .rotationState(RotationState.ALL)
        .appearanceBlock(GTBlocks.CASING_BRONZE_BRICKS)
        .recipeType('advanced_steam_mining_rig')
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("ABBBBBA", "ACCCCCA", "AAAAAAA", "AAAAAAA", "AAAAAAA", "AAAAAAA")
        .aisle("BEEEEEB", "CAAAAAC", "AAAAAAA", "AAAAAAA", "AAAAAAA", "AAAAAAA")
        .aisle("BEAAAEB", "FAAAAAF", "CAAAAAC", "AAAAAAA", "AAAAAAA", "AAAAAAA")
        .aisle("EAAAAAE", "EAAGAAE", "CAAGAAC", "CAAEAAC", "CHAEAHC", "ACCCCCA")
        .aisle("BEAAAEB", "FAAAAAF", "CAAAAAC", "AAAAAAA", "AAAAAAA", "AAAAAAA")
        .aisle("BEEEEEB", "CAAAAAC", "AAAAAAA", "AAAAAAA", "AAAAAAA", "AAAAAAA")
        .aisle("ABC@CBA", "ACCCCCA", "AAAAAAA", "AAAAAAA", "AAAAAAA", "AAAAAAA")
           .where("A", Predicates.any())
           .where("B", Predicates.blocks("gtceu:bronze_firebox_casing"))
           .where("C", Predicates.blocks("gtceu:steam_machine_casing").setMinGlobalLimited(24)
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS)))
           .where("E", Predicates.blocks("gtceu:industrial_steam_casing"))
           .where("F", Predicates.blocks("gtceu:bronze_pipe_casing"))
           .where("G", Predicates.blocks("gtceu:bronze_machine_casing"))
           .where("H", Predicates.blocks("gtceu:bronze_gearbox"))
           .where("@", Predicates.controller(Predicates.blocks(definition.get())))
        .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_bronze_plated_bricks', 'gtceu:block/machines/miner');
})

