GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create("gtsac:primitive_baking_oven", "primitive")
        .rotationState(RotationState.ALL)
        .recipeType('smoker')
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCC', 'CCC', 'CCC')
            .aisle('CCC', 'CAC', 'CAC')
            .aisle('ICO', 'CBC', "CCC")
            .where('C', Predicates.blocks('gtsac:primitive_baking_oven_bricks'))
            .where('A', Predicates.blocks('air').or(Predicates.blocks('cave_air')))
            .where('I', Predicates.blocks('gtceu:steam_input_bus'))
            .where('O', Predicates.blocks('gtceu:steam_output_bus'))
            .where('B', Predicates.controller(Predicates.blocks(definition.get())))
        .build())
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/machines/assembler');
})